### PR TITLE
use docker v2

### PR DESCRIPTION
**Pull request by nvdk**
since docker-compose is deprecated, updated the script to using `docker compose` (instead of `docker-compose`) command. Since this command doesn't print stopped containers by default, added `-a` switch to all `docker compose ps` commands as a safety measure.

This is a breaking change as it will not work for users on the (deprecated) docker v1

### CODE REVIEW

**Comment by nvdk** [comment]
@erikap @madnificent what needs to happen to get this merged?

**Comment by erikap** [comment]
We tried to verify what the breaking changes between `docker-compose` and `docker compose` are, but it seems Docker doesn't provide a complete list :crying_cat_face:  At least https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2 doesn't list the change in default we're encountering when running `docker compose ps`.

Nevertheless going through all usages of `docker compose` in the script, besides the stopped containers not being shown by default (which is fixed by adding `-a` option), it seems the currently used options are still supported and behave similar as before.

Also verified whether the commands where we inspect a docker-compose property of a container with `docker inspect`  (like for example [here](https://github.com/mu-semtech/mu-cli/blob/master/mu#L429)) still work. That seems to be the case.

**Comment by nvdk** [comment]
ah good catch

**Comment by madnificent** [comment]
New docker compose doesn't accept overlapping keys.  For those using the bash script of @nvdk to select docker-compose.yml, docker-compose.dev.yml and docker-compose.override.yml it makes most sense to select only those.

Current feature set is merged into @nvdk's branch and we'll merge that as such into current master.

For those on @nvdk's branch, it's safe to switch to this repository again.

**Pull request merged**
