### PR TITLE
warn if service isn't running yet

### LINKED ISSUE #11: Feature: detect and warn services that haven't booted yet
Currently the utility gives you a list of all the scripts available in the services if you run `mu script`.

But if the service hasn't booted up yet it will report as if the service didn't have any scripts. This should change and we should show a warning that it didn't booted up and that's why we can list the scripts available

### PR DESCRIPTION
**Pull request by nvdk**
fixes #11

### CODE REVIEW

**Comment by madnificent** [comment]
The container should exist, but it does not need to be up and running. The stack may be stopped, but containers must not be removed. Any ideas on a good naming to express that?

**Comment by nvdk** [comment]
ah indeed, "no container instance found" would perhaps be better?

**Comment by nvdk** [comment]
:thinking: would it be wrong for mu to create (but not start!) the container if no instance is found?

**Comment by nvdk** [comment]
I've updated the warning message

**Comment by madnificent** [comment]
Based on input from @erikap it turns out we can scratch the lot and create the images up front as you suggested.  We'll update the PR accordingly.

**Pull request merged**
